# Generated by Django 4.2.15 on 2024-09-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='reply',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
