# Generated by Django 4.2.15 on 2024-09-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_comment_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seasoninfo',
            name='description',
        ),
        migrations.AddField(
            model_name='animeinfo',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='comment',
            name='isedited',
            field=models.BooleanField(default=False),
        ),
    ]
