# Generated by Django 4.2.15 on 2024-09-12 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_seasoninfo_description_animeinfo_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animeinfo',
            name='banner',
            field=models.URLField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='animeinfo',
            name='img_src',
            field=models.URLField(max_length=250),
        ),
        migrations.AlterField(
            model_name='episodesinfo',
            name='episode_cover',
            field=models.URLField(max_length=250),
        ),
        migrations.AlterField(
            model_name='seasoninfo',
            name='season_banner',
            field=models.URLField(max_length=250),
        ),
        migrations.AlterField(
            model_name='seasoninfo',
            name='season_cover',
            field=models.URLField(max_length=250),
        ),
    ]
