# Generated by Django 4.2.15 on 2024-09-13 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_animeinfo_banner_alter_animeinfo_img_src_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animeinfo',
            name='banner',
            field=models.URLField(default='', max_length=350),
        ),
        migrations.AlterField(
            model_name='animeinfo',
            name='img_src',
            field=models.URLField(max_length=350),
        ),
        migrations.AlterField(
            model_name='animeinfo',
            name='status',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='episodesinfo',
            name='episode_cover',
            field=models.URLField(max_length=350),
        ),
        migrations.AlterField(
            model_name='episodesinfo',
            name='episode_link',
            field=models.URLField(max_length=350),
        ),
        migrations.AlterField(
            model_name='seasoninfo',
            name='season_banner',
            field=models.URLField(max_length=350),
        ),
        migrations.AlterField(
            model_name='seasoninfo',
            name='season_cover',
            field=models.URLField(max_length=350),
        ),
        migrations.AlterField(
            model_name='seasoninfo',
            name='status',
            field=models.CharField(max_length=15),
        ),
    ]
