# Generated by Django 4.2.15 on 2024-09-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_top_picks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('passkey', models.CharField(max_length=20)),
                ('recoverykey', models.CharField(max_length=50)),
                ('storagetype', models.CharField(max_length=10)),
                ('files', models.JSONField(blank=True, default=dict, null=True)),
                ('availsize', models.DecimalField(decimal_places=1, max_digits=3)),
                ('totalsize', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
    ]
