# Generated by Django 4.2.15 on 2024-09-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_storages'),
    ]

    operations = [
        migrations.AddField(
            model_name='storages',
            name='occupiedsize',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
            preserve_default=False,
        ),
    ]
